---
- name: dependency presents
  ansible.builtin.package:
    name:
      - unzip
      - gpg
      - dirmngr
    state: present
    update_cache: true

- name: create detector directory
  ansible.builtin.file:
    path: '{{ detector_dir }}'
    state: directory
    mode: '0644'

- name: download detector file(s)
  ansible.builtin.get_url:
    url: "{{ detector_baseurl }}{{ item }}"
    dest: "{{ detector_dir }}{{ item }}"
    mode: '0755'
    owner: root
    group: root
  with_items:
    - '{{ sh_detector }}'
    - '{{ sh_signature }}'

- name: gpg public key
  ansible.builtin.command: '{{ gpg_public_key }}'
  when: verify_gpg
  tags:
    - molecule-idempotence-notest

- name: gpg verify detector
  ansible.builtin.command: >
    'gpg --verify {{ detector_dir }}{{ sh_signature }}
    {{ detector_dir }}{{ sh_detector }}'
  when: verify_gpg
  tags:
    - molecule-idempotence-notest

- name: remove any detector run directory
  ansible.builtin.file:
    path: '{{ detector_dir }}{{ detector_run_dir }}'
    state: absent
  when: clean_run_before

- name: create detector run directory
  ansible.builtin.file:
    path: '{{ detector_dir }}{{ detector_run_dir }}'
    state: directory
    mode: '0644'

- name: run detector/scanner
  ansible.builtin.command: >
    '{{ detector_dir }}{{ sh_detector }} {{ detector_options }}
    --tmp {{ detector_dir }}{{ detector_run_dir }}'
  tags:
    - molecule-idempotence-notest

- name: files in detector run directory
  ansible.builtin.find:
    paths: '{{ detector_dir }}{{ detector_run_dir }}'
  register: vulnerable

- name: print vulnerable path(s) found
  ansible.builtin.debug:
    var: vulnerable

- name: remove detector directory
  ansible.builtin.file:
    path: '{{ detector_dir }}'
    state: absent
  when: delete_after
