---
- name: dependency present
  ansible.builtin.package:
    name: unzip
    state: present
    update_cache: true

- name: create detector directory
  ansible.builtin.file:
    path: '{{ detector_dir }}'
    state: directory

- name: download detector file(s)
  ansible.builtin.get_url:
    url: "{{ detector_baseurl }}{{ item }}"
    dest: "{{ detector_dir }}{{ item }}"
    mode: '0755'
    owner: root
    group: root
  with_items:
    - '{{ sh_detector }}'
    - '{{ sh_signature }}'

- name: gpg public key
  ansible.builtin.shell: '{{ gpg_public_key }}'
  when: verify_gpg == true

- name: gpg verify detector
  ansible.builtin.shell: >
    'gpg --verify {{ detector_dir }}{{ sh_signature }} 
    {{ detector_dir }}{{ sh_detector }}'
  when: verify_gpg == true

- name: remove any detector run directory
  ansible.builtin.file:
    path: '{{ detector_dir }}{{ detector_run_dir }}'
    state: absent
  when: clean_run_before == true

- name: create detector run directory
  ansible.builtin.file:
    path: '{{ detector_dir }}{{ detector_run_dir }}'
    state: directory

- name: run detector/scanner
  ansible.builtin.shell: >
    '{{ detector_dir }}{{ sh_detector }} {{ detector_options }} 
    --tmp {{ detector_dir }}{{ detector_run_dir }}'

- name: files in detector run directory
  ansible.builtin.find:
    paths: '{{ detector_dir }}{{ detector_run_dir }}'
  register: vulnerable

- name: print vulnerable path(s) found
  ansible.builtin.debug:
    var: vulnerable

- name: remove detector directory
  ansible.builtin.file:
    path: '{{ detector_dir }}'
    state: absent
  when: delete_after == true
